---
- name: Install Packages needed for the node
  yum: pkg={{item}} state=installed
  with_items:
  - epel-release
  - vim
  - screen
  - net-tools
  - htop
  - git
  - rsync
  - wget
  - curl
  - nfs-utils
  - openssh-server
  - libvirt
  - virt-manager
  - ansible
  - kexec-tools
  - nmap
  - qemu-kvm
  - xauth
  - dejavu-lgc-sans-fonts
  - nagios-plugins-load.x86_64
  - nagios-plugins-nrpe.x86_64
  - xauth 
  - mlocate
  - wireshark
  - nmap

